hw2
altengofso/java-course-2023-backend pull request #2
Opened 2024-02-25 16:21 UTC by altengofso

2024-02-25 17:43 UTC, SHvatov requested changes
@altengofso оставил пару минорных комментариев, погляди плиз.

2024-02-25 17:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +        return response == null ? null : response.updatedAt();
Честно скажу, я не сторонник обработки исключений в клиентах. Часто бывает такое, что есть один метод, который используется в двух сервисах. Только в первом сервисе ошибка при вызове API не критична, и мы ее логируем и игнорим, а вот во втором ошибка должна приводить к ошибке нашего API. Ты же не даешь вариативности.

2024-02-25 17:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +            log.error(e.getMessage());
`log.error("<осмысленное сообщение>", e)`

Честно говоря, у веб-клиентов исключения реализованы очень куцо и все, что в них есть - статус + урл. Этого, зачастую, не хватает для анализа. \+ осмысленное сообщение поможет быстрее понять, где именно ошибка произошла.

2024-02-25 17:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/ResourceClient.java
> +public interface ResourceClient {
1. Название очень расплывчатое, какие ресурсы запрашивает данный клиент?
2. Честно говоря, мне не очень нравится, что клиент реализуют как бы бизнесовый интерфейс. Клиенты в первую очередь про выполнение запросов, а тут все-таки интерфейс, который нужен для реализации бизнес-логики. Я бы, честно говоря, сделал отдельный менеджер, в котором бы через chain of responsibility решал, кто из клиентов должен обработать урл.

2024-02-25 17:43 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +    public GithubClient getGithubClient(ApplicationConfig applicationConfig) {
Почему бы клиенты не пометить как @Component?

2024-02-28 15:02 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +        return response == null ? null : response.updatedAt();
интересно, что мне idea не сделала никакого замечания по поводу возможного исключения при использовании метода get.
мне это показалось странным, потому что точно должна возникать ошибка при отсутствии интернета, например.
что я и проверил. отключил интернет, запустил код и получил эту ошибку.
кстати с вполне читаемым сообщением, что не удалось разрешить имя api.github.com.
но раз уж клиент только отправляет запросы, а по другому комментарию добавляю менеджера этих клиентов, который определяет по ссылке, какой использовать, то тут обработку убираю)

2024-02-28 15:06 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +            log.error(e.getMessage());
развернуто ответил в предыдущем комментарии

2024-02-28 21:44 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +    public GithubClient getGithubClient(ApplicationConfig applicationConfig) {
так указано в задании "зарегистрируйте клиентов как бины в отдельном файле ClientConfiguration при помощи аннотации @Bean."

2024-02-28 21:55 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/client/ResourceClient.java
> +public interface ResourceClient {
В задании просили создать HTTP-клиентов для Github и Stackoverflow на основе WebClient. Поэтому и название такое выбрал ...Client. 
В задании есть даже пример интерфейса подобного клиента:
interface GitlabClient {
    UserResponse fetchUser(String user);
}
К замечанию прислушался и честно тоже сначала хотел сделать автоматический выбор клиент по ссылке.
Итого теперь:
Есть интерфейс ApiClient с методами boolean canRespond и ClientResponse getResponse
Есть абстрактный класс AbstractApiClient, которые реализует общую логику всех клиентов.
Есть отдельные клиенты GithubApiClient и StackoverflowApiClient, унаследованные от абстрактного клиента, с дописанной уникальной логикой работы.
Клиент возвращает время обернутое в *Response класс, как требовалось в задании.
Добавлен ClientService, в который инжектится список всех доступных клиентов и который умеет выбирать подходящих для обработки ссылки клиент.
Добавлен ScrapperService, который получает клиента от ClientService и получает ClientResponse от этого клиента.
Тесты скорректированы в соответствии с изменениями и дополнены.

Кажется, это все должно решить описанные тобой проблемы)

2024-02-29 19:24 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ClientConfiguration.java
> +    public GithubClient getGithubClient(ApplicationConfig applicationConfig) {
Эх, ох уж это задание. 🆗

2024-02-29 19:26 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/GithubClient.java
> +            log.error(e.getMessage());
не соглашусь, одно дело резолвинг днса, а другое дело 4хх или 5хх) если удастся сымитировать что-то такое и показать, что в логах реально будет что-то нормальное, по чему сразу можно будет понять причину, то я соглашусь) кстати, это можно сделать через тест)

2024-02-29 19:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/ResourceClient.java
> +public interface ResourceClient {
Про название я имел в виду `ResourseClient`. Это как `КлиентДляАпи`, что как бы верно, вот только что это дает мне, как пользователю этого кода?)

2024-02-29 19:27 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/client/ApiClient.java
> +    boolean canRespond(String link);
`canAccess`, боюсь данный клиент не может гарантировать, что запрашиваемый ресурс ответит)

2024-02-29 19:28 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Хм, а ты можешь объяснить, почему это работает?) Вроде как бин на поле, почему же он создается?

2024-02-29 19:29 UTC, SHvatov requested changes
@altengofso, посмотрел, отписался, интересует меня ответ на вопрос про @Bean на поле)

2024-03-01 08:52 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Думаю, что создается, потому что эти рекорды находятся внутри аннотации @ConfigurationProperties.
Эта аннотация запускает конструктор от всех параметров, если он является единственным конструктором в классе. Для этих рекордов это как раз справедливо.
Проверить это можно, переопределив конструктор от всех параметров, например, так:
public record Scheduler(boolean enable, @NotNull Duration interval, @NotNull Duration forceCheckDelay) {
        public Scheduler(boolean enable, Duration interval, Duration forceCheckDelay) {
            this.enable = enable;
            this.interval = interval;
            this.forceCheckDelay = forceCheckDelay;
            System.out.println("HELLO");
        }
При этом убрать @Bean и @Scheduled, чтобы не возникло ошибки при запуске приложения.
И запустить.
Тогда в логе можно будет увидеть HELLO, когда выполнится конструктор этого рекорда, хотя явно его нигде не вызывали.
11:48:33.897 INFO  [restartedMain                 ] {} apper.ScrapperApplication -- No active profile set, falling back to 1 default profile: "default" 
HELLO
11:48:36.480 DEBUG [restartedMain                 ] {} uestMappingHandlerMapping -- 2 mappings in 'requestMappingHandlerMapping' 

А @Bean, думаю, в этом случае просто помечает созданный рекорд, как бин. И благодаря SpEL можно использовать его по имени, вызывать его методы и методы его полей. При этом нигде ошибки применения @Bean к полю именно рекорда не возникает, в отличие от обычного класса.
Можно было бы обойтись без бина. Например, так @Scheduled(fixedDelayString = "${app.scheduler.interval}"). Просто обратиться напрямую в значению поля в файле свойств. Но тогда и значение должно было бы быть сразу в миллисекундах.

Честно, до использования видел подсказку в чате. Сейчас где-то найти какое-то документальное подтверждение не могу. Кроме описания аннотации @ConfigurationProperties https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/ConfigurationProperties.html и этой статьи https://www.baeldung.com/configuration-properties-in-spring-boot#immutable-configurationproperties-binding

2024-03-01 09:06 UTC, altengofso commented on scrapper/src/main/java/edu/java/scrapper/client/ApiClient.java
> +    boolean canRespond(String link);
исправил

2024-03-03 18:21 UTC, SHvatov commented on scrapper/src/main/java/edu/java/scrapper/configuration/ApplicationConfig.java
> +    @Bean
Все немного прозаичнее - https://stackoverflow.com/questions/67074911/what-annotation-targets-are-applicable-to-java-records. Если кратко - аннотации на рекордах пропагируются на сгенерированные методы, поэтому будет метод duration(), помеченный как бин. Чисто ради интереса можно попробовать заменить рекорд на обычный POJO)

Давай все-таки обращаться к duration через путь в конфиг. файле) Так намного понятнее и очевиднее.

2024-03-03 18:22 UTC, SHvatov approved these changes
@altengofso поменяй, плиз, spel на путь, и можно будет мержить)

2024-03-03 19:54 UTC, merged